
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-MenuItemReview-Edit","number":117,"title":"Edit Pages for MenuItemReview Completed","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/117"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-UCSBDiningCommonsMenuItems-EditPagesAndTests","number":116,"title":"edit page and tests for menu items","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/116"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-PlaceHolder","number":108,"title":"Eli place holder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/108"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-Table","number":107,"title":"Eli table","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/107"}]
