
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Index","number":72,"title":"Added Recommendation Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/72"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Placeholders","number":71,"title":"Add Placeholders to Navbar and App","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/71"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-TableComponent","number":70,"title":"Add Recommendation Request Table Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/70"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-FormComponent","number":69,"title":"Add RecommendationRequest Form Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/69"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Fixtures","number":68,"title":"Add Recommendation Request Fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/68"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-CRUD","number":67,"title":"Add RecommendationRequest Backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/67"}]
