
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-Appjs","number":105,"title":"Tony appjs","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/105"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-appnavbar","number":104,"title":"Tony appnavbar","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/104"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Placeholders","number":103,"title":"Jason help request placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/103"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-Forms","number":101,"title":"Eli forms","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/101"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-TableComponent","number":100,"title":"Help Request Table Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/100"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Edit","number":74,"title":"Add RecommendationRequest Edit page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/74"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Create","number":73,"title":"Added Index for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/73"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Index","number":72,"title":"Added Recommendation Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/72"}]
