
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-H05","number":139,"title":"Integration and End-To-End Tests for MenuItemReviews","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/139"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-UpdatedH05","number":138,"title":"Jason Updated h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/138"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-HMK5","number":137,"title":"Tony hmk5","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/137"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-H05","number":135,"title":"Added the integration and E2E tests for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/135"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addTests","number":134,"title":"Add Integration & End-To-End tests for Recommendation Requests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/134"}]
