
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-MenuItemReview-Form","number":87,"title":"Form and Tests for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/87"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-UCSBDiningCommonsMenuItems-Form","number":84,"title":"fixed form and created tests, also fixed my fixtures file","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/84"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Edit","number":74,"title":"Add RecommendationRequest Edit page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/74"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Create","number":73,"title":"Added Index for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/73"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Index","number":72,"title":"Added Recommendation Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/72"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Placeholders","number":71,"title":"Add Placeholders to Navbar and App","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/71"}]
