
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-EditPage","number":115,"title":"Jason HelpRequestEditPage","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/115"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-CreatePage","number":112,"title":"Jason HelpRequestCreatePage","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/112"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-MenuItemReview-Index","number":111,"title":"finished Index page for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/111"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-MenuItemReview-Create","number":110,"title":"Finished Create page for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/110"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-StorybookFixes","number":109,"title":"Jason help request storybook fixes","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/109"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-PlaceHolder","number":108,"title":"Eli place holder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/108"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-Table","number":107,"title":"Eli table","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/107"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Placeholders","number":103,"title":"Jason help request placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/103"}]
