
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-Index-Update","number":121,"title":"Overhauled done-field dropdown, Corrected IndexPage Done error","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/121"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-EditPage","number":120,"title":"Edit Page and Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/120"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli-PlaceHolder","number":108,"title":"Eli place holder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/108"}]
