
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-CRUD","number":67,"title":"Add RecommendationRequest Backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/67"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-COPY","number":66,"title":"Copied Backend files for CRUD for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/66"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"TONY-PRFORCOPYPASTE","number":65,"title":"copypaste","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-4/pull/65"}]
